# Generated by Django 4.0.1 on 2022-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_categories',
            field=models.ManyToManyField(through='news.PostCategory', to='news.Category'),
        ),
    ]
