# Generated by Django 4.0.1 on 2022-02-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_categoryusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryUsers',
        ),
    ]
