# Generated by Django 4.0.1 on 2022-02-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_delete_categoryusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_categories',
            new_name='categories',
        ),
    ]
